x-service-common: &service-common
  build:
    dockerfile: Dockerfile
    context: ./backend
  restart: always
  env_file:
    - .env
  volumes:
    - ./backend/app:/app
  command: |
    sh -c "
    alembic upgrade head && \      
    uvicorn main:app --port=12321 --host=0.0.0.0 --reload
    "
  networks:
    - main_network

services:

  backend1:
    <<: *service-common
    container_name: backend1
    hostname: backend1
    ports:
      - "12321:12321"

  backend2:
    <<: *service-common
    container_name: backend2
    hostname: backend2
    ports:
      - "12322:12321"

  nginx_local:
    image: nginx:alpine
    container_name: nginx_local
    restart: always
    ports:
      - "80:80"
    networks:
      - main_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  main_network:
    driver: bridge