"""add storage

Revision ID: e7519ea7afdb
Revises:
Create Date: 2025-07-05 10:02:16.816050

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e7519ea7afdb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tourismrequesthistorys",
        sa.Column("text", sa.String(length=2048), nullable=False),
        sa.Column("exclude", sa.String(length=2048), nullable=False),
        sa.Column("num_places", sa.Integer(), nullable=False),
        sa.Column(
            "response_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tourismrequesthistorys_text"),
        "tourismrequesthistorys",
        ["text"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tourismrequesthistorys_text"), table_name="tourismrequesthistorys"
    )
    op.drop_table("tourismrequesthistorys")
    # ### end Alembic commands ###
